package cluster

import "errors"

var (
	ErrClusterNameRequired             = errors.New("cluster name is required")
	ErrClusterGenerationNegative       = errors.New("cluster generation must be non-negative")
	ErrClusterEpochNegative            = errors.New("cluster epoch must be non-negative")
	ErrClusterObservedAtRequired       = errors.New("cluster observed time is required")
	ErrClusterPhaseRequired            = errors.New("cluster phase is required")
	ErrMaintenanceUpdatedAtRequired    = errors.New("maintenance updated time is required")
	ErrMemberNameRequired              = errors.New("member name is required")
	ErrMemberPriorityNegative          = errors.New("member priority must be non-negative")
	ErrMemberRoleRequired              = errors.New("member role is required")
	ErrMemberStateRequired             = errors.New("member state is required")
	ErrMemberTimelineNegative          = errors.New("member timeline must be non-negative")
	ErrMemberLagNegative               = errors.New("member lag must be non-negative")
	ErrMemberPortOutOfRange            = errors.New("member port must be between 1 and 65535")
	ErrMemberLastSeenAtRequired        = errors.New("member last seen time is required")
	ErrMemberAPIURLInvalid             = errors.New("member api url is invalid")
	ErrOperationIDRequired             = errors.New("operation id is required")
	ErrOperationKindRequired           = errors.New("operation kind is required")
	ErrOperationStateRequired          = errors.New("operation state is required")
	ErrOperationResultRequired         = errors.New("operation result is required")
	ErrOperationRequestedAtRequired    = errors.New("operation requested time is required")
	ErrHistoryOperationIDRequired      = errors.New("history operation id is required")
	ErrHistoryTimelineNegative         = errors.New("history timeline must be non-negative")
	ErrHistoryFinishedAtRequired       = errors.New("history finished time is required")
	ErrScheduledSwitchoverAtRequired   = errors.New("scheduled switchover time is required")
	ErrScheduledSwitchoverFromRequired = errors.New("scheduled switchover source member is required")
	ErrInvalidFailoverMode             = errors.New("failover mode is invalid")
	ErrInvalidClusterPhase             = errors.New("cluster phase is invalid")
	ErrInvalidMemberRole               = errors.New("member role is invalid")
	ErrInvalidMemberState              = errors.New("member state is invalid")
	ErrInvalidOperationKind            = errors.New("operation kind is invalid")
	ErrInvalidOperationState           = errors.New("operation state is invalid")
	ErrInvalidOperationResult          = errors.New("operation result is invalid")
	ErrInvalidSynchronousMode          = errors.New("postgres synchronous mode is invalid")
)
