---
- name: Configure external etcd DCS nodes for PACMAN
  hosts: dcs_nodes
  become: true
  roles:
    - role: external_etcd

- name: Configure PostgreSQL nodes for PACMAN
  hosts: postgres_nodes
  become: true
  roles:
    - role: postgresql

- name: Configure pacmand on PostgreSQL nodes
  hosts: postgres_nodes
  become: true
  roles:
    - role: pacman

- name: Configure vip-manager on PostgreSQL nodes
  hosts: postgres_nodes
  become: true
  roles:
    - role: vip_manager
