package controlplane

import "errors"

var (
	ErrMemberRegistrationTimeRequired      = errors.New("member registration time is required")
	ErrClusterSpecRequired                 = errors.New("cluster desired state is not initialized")
	ErrFailoverObservedStateRequired       = errors.New("failover evaluation requires observed cluster state")
	ErrAutomaticFailoverNotAllowed         = errors.New("automatic failover is not allowed by cluster policy")
	ErrFailoverPrimaryUnknown              = errors.New("failover cannot proceed without a current primary")
	ErrFailoverPrimaryHealthy              = errors.New("failover primary has not been confirmed failed")
	ErrFailoverQuorumUnavailable           = errors.New("failover quorum is not reachable")
	ErrFailoverMaintenanceEnabled          = errors.New("failover is blocked while maintenance mode is enabled")
	ErrFailoverOperationInProgress         = errors.New("failover is blocked while another cluster operation is active")
	ErrFailoverNoEligibleCandidates        = errors.New("no eligible failover candidates are available")
	ErrFailoverIntentRequired              = errors.New("failover execution requires an active failover intent")
	ErrFailoverPromotionExecutorRequired   = errors.New("failover execution requires a promotion executor")
	ErrFailoverFencingHookRequired         = errors.New("failover policy requires a fencing hook")
	ErrFailoverCandidateUnknown            = errors.New("failover candidate is not present in observed state")
	ErrFailoverIntentChanged               = errors.New("failover intent changed during execution")
	ErrSwitchoverObservedStateRequired     = errors.New("switchover validation requires observed cluster state")
	ErrSwitchoverTargetRequired            = errors.New("switchover target standby is required")
	ErrSwitchoverTargetUnknown             = errors.New("switchover target standby is not present in observed state")
	ErrSwitchoverTargetNotReady            = errors.New("switchover target standby is not ready")
	ErrSwitchoverTargetIsCurrentPrimary    = errors.New("switchover target standby is already the current primary")
	ErrSwitchoverPrimaryUnknown            = errors.New("switchover cannot proceed without a current primary")
	ErrSwitchoverPrimaryUnhealthy          = errors.New("switchover requires a healthy current primary")
	ErrSwitchoverOperationInProgress       = errors.New("switchover is blocked while another cluster operation is active")
	ErrSwitchoverSchedulingNotAllowed      = errors.New("scheduled switchover is not allowed by cluster policy")
	ErrSwitchoverIntentRequired            = errors.New("switchover execution requires an active switchover intent")
	ErrSwitchoverDemotionExecutorRequired  = errors.New("switchover execution requires a demotion executor")
	ErrSwitchoverPromotionExecutorRequired = errors.New("switchover execution requires a promotion executor")
	ErrSwitchoverIntentChanged             = errors.New("switchover intent changed during execution")
	ErrSwitchoverExecutionNotReady         = errors.New("switchover cannot execute before its scheduled time")
	ErrRejoinObservedStateRequired         = errors.New("rejoin assessment requires observed cluster state")
	ErrRejoinTargetRequired                = errors.New("rejoin member is required")
	ErrRejoinTargetUnknown                 = errors.New("rejoin member is not present in observed state")
	ErrRejoinStrategyUndetermined          = errors.New("rejoin strategy is not ready to be decided")
	ErrRejoinRewindExecutorRequired        = errors.New("rejoin rewind requires a rewind executor")
	ErrRejoinOperationInProgress           = errors.New("rejoin is blocked while another cluster operation is active")
	ErrRejoinRewindNotRequired             = errors.New("rejoin does not require pg_rewind")
	ErrRejoinRecloneRequired               = errors.New("rejoin requires a full reclone instead of pg_rewind")
	ErrLeaderCandidateRequired             = errors.New("leader candidate is required")
	ErrLeaderCandidateUnknown              = errors.New("leader candidate is not registered")
	ErrSourceOfTruthStateRequired          = errors.New("cluster source of truth requires desired or observed state")
	ErrSourceOfTruthUpdatedAtRequired      = errors.New("cluster source of truth updated time is required")
	ErrSourceOfTruthClusterNameMismatch    = errors.New("cluster source of truth cluster names must match")
)
