package controlplane

const (
	reasonCurrentPrimary                        = "member is the current primary"
	reasonCurrentPrimaryUnknown                 = "current primary is unknown"
	reasonCurrentPrimaryUnhealthy               = "current primary is not healthy"
	reasonRoleNotPromotable                     = "member role is not promotable"
	reasonMemberUnhealthy                       = "member is not healthy"
	reasonMemberDoesNotRequireRejoin            = "member does not require rejoin"
	reasonMemberRequiresRejoin                  = "member requires rejoin"
	reasonNoFailoverTagged                      = "member is tagged no-failover"
	reasonLagExceedsFailoverPolicy              = "member replication lag exceeds failover policy"
	reasonTimelineMismatch                      = "member timeline does not match current primary"
	reasonTimelineAheadOfCurrentPrimary         = "member timeline is ahead of current primary"
	reasonRoleNotStandby                        = "member role is not a standby"
	reasonStateNotReadyForSwitchover            = "member state is not ready for switchover"
	reasonLagExceedsSwitchoverMaximum           = "member replication lag exceeds configured maximum"
	reasonNodeStateNotObserved                  = "member node state has not been observed"
	reasonCurrentPrimaryStateNotObserved        = "current primary node state has not been observed"
	reasonPostgresNotManaged                    = "member postgres is not managed"
	reasonPostgresNotUp                         = "member postgres is not up"
	reasonRecoveryStateUnknown                  = "member recovery state is unknown"
	reasonNotInRecovery                         = "member is not currently in recovery"
	reasonPostgresRoleNotStandby                = "member postgres role is not a standby"
	reasonMemberSystemIdentifierUnknown         = "member system identifier is unknown"
	reasonCurrentPrimarySystemIdentifierUnknown = "current primary system identifier is unknown"
	reasonMemberTimelineUnknown                 = "member timeline is unknown"
	reasonCurrentPrimaryTimelineUnknown         = "current primary timeline is unknown"
	reasonSystemIdentifierMismatch              = "member system identifier does not match current primary"
)
