run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
