sonar.projectKey=polkiloo_pacman
sonar.organization=polkiloo
sonar.projectName=pacman
sonar.sourceEncoding=UTF-8

sonar.sources=cmd,internal
sonar.tests=cmd,internal,test

sonar.exclusions=**/*_test.go
sonar.test.inclusions=**/*_test.go,test/**/*.go
sonar.go.coverage.reportPaths=coverage.out
