[dcs_nodes]
alpha-dcs ansible_host=pacman-dcs ansible_connection=local ansible_python_interpreter=/usr/bin/python3 etcd_name=alpha-dcs

[postgres_nodes]
alpha-1 ansible_host=pacman-primary ansible_connection=local ansible_python_interpreter=/usr/bin/python3 pacman_node_name=alpha-1
alpha-2 ansible_host=pacman-replica ansible_connection=local ansible_python_interpreter=/usr/bin/python3 pacman_node_name=alpha-2

[all:vars]
ansible_user=root
pacman_cluster_name=alpha
pacman_initial_primary=alpha-1
