scope: alpha
name: patroni-1

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni-primary:8008

etcd3:
  hosts:
    - patroni-dcs:2379
    - patroni-dcs-2:2379
    - patroni-dcs-3:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 0.0.0.0/0 scram-sha-256
    - host all all 0.0.0.0/0 scram-sha-256

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni-primary:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/17/bin
  authentication:
    replication:
      username: replicator
      password: patroni-replication-password
    superuser:
      username: postgres
      password: patroni-demo-password
  parameters:
    hot_standby: "on"
    max_replication_slots: 10
    max_wal_senders: 10
    wal_level: replica
