---
pacman_package_name: pacman
pacman_package_url: ""
pacman_download_path: /var/tmp/pacman.rpm
pacman_disable_gpg_check: false
pacman_api_port: 8080
pacman_control_port: 9090

pacman_tls_enabled: false
pacman_tls_dir: /etc/pacman/tls
pacman_tls_ca_src: ""
pacman_tls_cert_src: ""
pacman_tls_key_src: ""
pacman_tls_ca_path: "{{ pacman_tls_dir }}/ca.crt"
pacman_tls_cert_path: "{{ pacman_tls_dir }}/node.crt"
pacman_tls_key_path: "{{ pacman_tls_dir }}/node.key"
pacman_tls_server_name: ""
pacman_tls_insecure_skip_verify: false
pacman_security_member_mtls_enabled: false

pacman_admin_token_path: /etc/pacman/admin-token
pacman_admin_token_inline: change-me-before-production
pacman_admin_token_source_files: []
pacman_admin_token_active_id: current

pacmand_service_name: pacmand
pacmand_binary_path: /usr/bin/pacmand
pacmand_service_user: postgres
pacmand_service_group: postgres
pacmand_config_dir: /etc/pacman
pacmand_config_path: /etc/pacman/pacmand.yaml
pacmand_state_dir: /var/lib/pacman
pacmand_token_dir: "{{ pacmand_config_dir }}/tokens"
pacmand_environment: {}
pacman_manage_service: true
