package config

import "errors"

var (
	ErrUnsupportedAPIVersion               = errors.New("config apiVersion is unsupported")
	ErrUnexpectedKind                      = errors.New("config kind is invalid")
	ErrNodeNameRequired                    = errors.New("config node name is required")
	ErrNodeRoleRequired                    = errors.New("config node role is required")
	ErrNodeRoleInvalid                     = errors.New("config node role is invalid")
	ErrNodeAPIAddressRequired              = errors.New("config node apiAddress is required")
	ErrNodeAPIAddressInvalid               = errors.New("config node apiAddress is invalid")
	ErrNodeControlAddressRequired          = errors.New("config node controlAddress is required")
	ErrNodeControlAddressInvalid           = errors.New("config node controlAddress is invalid")
	ErrDCSClusterNameMismatch              = errors.New("config dcs clusterName must match bootstrap clusterName")
	ErrTLSCertFileRequired                 = errors.New("config tls certFile is required")
	ErrTLSKeyFileRequired                  = errors.New("config tls keyFile is required")
	ErrSecurityAdminBearerTokenRequired    = errors.New("config security adminBearerToken or adminBearerTokenFile is required")
	ErrSecurityAdminBearerTokenConflict    = errors.New("config security adminBearerToken and adminBearerTokenFile are mutually exclusive")
	ErrSecurityMemberMTLSRequiresTLS       = errors.New("config security memberMTLSEnabled requires tls.enabled")
	ErrSecurityMemberMTLSCAFileRequired    = errors.New("config security memberMTLSEnabled requires tls caFile")
	ErrSecurityMemberMTLSBootstrapRequired = errors.New("config security memberMTLSEnabled requires bootstrap expectedMembers")
	ErrSecurityMemberMTLSNodeUnknown       = errors.New("config security memberMTLSEnabled requires node name in bootstrap expectedMembers")
	ErrSensitiveConfigFilePermissions      = errors.New("config file containing inline secrets must not be readable by group or others")
	ErrPostgresDataDirRequired             = errors.New("config postgres dataDir is required")
	ErrPostgresListenAddressRequired       = errors.New("config postgres listenAddress is required")
	ErrPostgresListenAddressInvalid        = errors.New("config postgres listenAddress is invalid")
	ErrPostgresPortOutOfRange              = errors.New("config postgres port must be between 1 and 65535")
	ErrPostgresReplicationUserRequired     = errors.New("config postgres replicationUser is required when replicationPassword is set")
	ErrUnsafeClusterParameterOverride      = errors.New("config postgres parameters contain unsafe local override")
	ErrBootstrapClusterNameRequired        = errors.New("config bootstrap clusterName is required")
	ErrBootstrapInitialPrimaryRequired     = errors.New("config bootstrap initialPrimary is required")
	ErrBootstrapInitialPrimaryUnknown      = errors.New("config bootstrap initialPrimary must be listed in expectedMembers")
	ErrBootstrapSeedAddressRequired        = errors.New("config bootstrap seedAddresses must contain at least one address")
	ErrBootstrapSeedAddressInvalid         = errors.New("config bootstrap seedAddresses contain an invalid address")
	ErrBootstrapExpectedMembersRequired    = errors.New("config bootstrap expectedMembers must contain at least one member")
	ErrBootstrapExpectedMemberInvalid      = errors.New("config bootstrap expectedMembers contain an empty member name")
)
